spring:
  application:
    name: "Drones manager"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/musuala_test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/2022/09/changelog-master.xml
server:
  port: 8082
file:
  upload:
    dir: "files/images"